# Generated by Django 3.2.6 on 2021-09-26 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20210925_0916'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participantprofile',
            name='seminars',
        ),
    ]
