# Generated by Django 3.2.6 on 2021-09-07 17:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyresult',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='surveys', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='surveyresult',
            name='backend_reason',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='surveyresult',
            name='grade',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='surveyresult',
            name='major',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='surveyresult',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
