# Generated by Django 3.2.6 on 2021-09-26 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_remove_participantprofile_seminars'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instructorprofile',
            name='charge',
        ),
    ]
