# Generated by Django 3.2.6 on 2021-09-25 09:16

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Seminar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('capacity', models.IntegerField(default=0)),
                ('count', models.IntegerField(default=0)),
                ('time', models.TimeField(default=datetime.time(0, 0))),
                ('online', models.BooleanField(default=True)),
                ('instructors', models.JSONField(null=True)),
                ('participants', models.JSONField(null=True)),
                ('participant_count', models.IntegerField(null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at_column', models.DateTimeField(auto_now_add=True)),
                ('joined_at', models.DateTimeField(null=True)),
                ('is_active', models.BooleanField(null=True)),
                ('dropped_at', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserSeminar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('participant', 'participant'), ('instructor', 'instructor')], max_length=15, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('joined_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('dropped_at', models.DateTimeField(null=True)),
                ('updated_at_column', models.DateTimeField(auto_now=True)),
                ('seminar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seminar', to='seminar.seminar')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
