# Generated by Django 3.2.6 on 2021-09-26 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seminar', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seminar',
            name='dropped_at',
        ),
        migrations.RemoveField(
            model_name='seminar',
            name='instructors',
        ),
        migrations.RemoveField(
            model_name='seminar',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='seminar',
            name='joined_at',
        ),
        migrations.RemoveField(
            model_name='seminar',
            name='participant_count',
        ),
        migrations.RemoveField(
            model_name='seminar',
            name='participants',
        ),
        migrations.RemoveField(
            model_name='userseminar',
            name='joined_at',
        ),
    ]
